# Generated by Django 5.1.5 on 2025-03-15 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='uploaded_pdfs/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('parse_type', models.CharField(blank=True, choices=[('references_only', 'References Only'), ('methods_tables_only', 'Methods & Tables Only'), ('both', 'Both References & Methods+Tables')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
