# Generated by Django 5.1.5 on 2025-03-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pdf_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
