# Generated by Django 5.1.5 on 2025-03-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paper_pdf_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='methods_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='references_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='summary_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='tables_json',
            field=models.TextField(blank=True),
        ),
    ]
